require:
  - rubocop-rails

Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Exclude:
    - db/migrate/*.rb

Style/Documentation:
  Exclude:
    - db/migrate/*.rb

Metrics/BlockLength:
  AllowedMethods: ["describe", "context", "it", "feature", "scenario"]

Style/StringLiterals:
  Exclude:
    - Gemfile
    - db/schema.rb

AllCops:
  NewCops: enable
  DisplayCopNames: true
      # Exclude:
      # - db/schema.rb
      # - db/seeds.rb
      # - bin/**/*
      # - node_modules/**/*

      # Style/StringLiterals:
      # Enabled: false

      # Style/Documentation:
      # Enabled: false

      # Layout/IndentationConsistency:
      #  enforcedstyle: indented_internal_methods
      # Exclude:
      # - config/routes.rb

      # Rails/FilePath:
      #   Exclude:
      #   - config/environments/development.rb

      # Style/BlockComments:
      # Exclude:
      # - spec/spec_helper.rb

      # Layout/LineLength:
      # Max: 120
      # Exclude:
      # - spec/**/*.rb

      # Style/NumericLiterals:
      # Exclude:
      #   - db/schema.rb
      #   - db/seeds.rb
